-- Docker startup scripts often run in CDB$ROOT. Put objects in FREEPDB1
-- as SYSTEM so the Flask app can connect with SYSTEM / FREEPDB1.
BEGIN
    IF SYS_CONTEXT('USERENV', 'CON_NAME') <> 'FREEPDB1' THEN
        EXECUTE IMMEDIATE 'ALTER SESSION SET CONTAINER = FREEPDB1';
    END IF;
END;
/

ALTER SESSION SET CURRENT_SCHEMA = SYSTEM;

-- Table for Hasan (Item 101)
CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table for Daniel (Items 102 & 103)
CREATE TABLE MenuItems (
    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(255),
    price NUMBER(8, 2) NOT NULL,
    category VARCHAR2(50),
    is_available NUMBER(1) DEFAULT 1
);

-- Sample food for the menu page
INSERT INTO MenuItems (name, description, price, category, is_available)
VALUES ('Cheeseburger', 'Beef patty, cheddar, lettuce, tomato', 9.99, 'Burgers', 1);
INSERT INTO MenuItems (name, description, price, category, is_available)
VALUES ('Veggie Burger', 'Black bean patty with avocado', 10.49, 'Burgers', 1);
INSERT INTO MenuItems (name, description, price, category, is_available)
VALUES ('French Fries', 'Crispy salted fries', 3.99, 'Sides', 1);
INSERT INTO MenuItems (name, description, price, category, is_available)
VALUES ('Chicken Tenders', 'Three crispy tenders with dipping sauce', 8.49, 'Sides', 1);
INSERT INTO MenuItems (name, description, price, category, is_available)
VALUES ('Cola', 'Fountain drink', 1.99, 'Drinks', 1);
INSERT INTO MenuItems (name, description, price, category, is_available)
VALUES ('Lemonade', 'Freshly squeezed', 2.49, 'Drinks', 1);

COMMIT;